name: Terraform Filter

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose env"
        required: true
        default: "dv"
        type: choice
        options:
          - dv
          - pr
      provider:
        description: "Choose provider"
        required: true
        default: "common_infrastructure"
        type: choice
        options:
          - common_infrastructure
          - services

  push:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

jobs:
  manual-trigger:
    if: github.event_name == 'workflow_dispatch'
    name: Manual Terraform Deploy - ${{ inputs.env }} - ${{ inputs.provider }}
    uses: ./.github/workflows/exec-pipeline.yml
    with:
      env: ${{ inputs.env }}
      provider: ${{ inputs.provider }}
      tfvars_path: infrastructure/deployment/${{ inputs.provider }}/varvalues/${{ inputs.env }}.tfvars
      trigger_path: infrastructure/deployment/${{ inputs.provider }}/

  auto-trigger:
    if: github.event_name != 'workflow_dispatch'
    name: Auto Terraform Deploy - ${{ matrix.env }} - ${{ matrix.provider }}
    uses: ./.github/workflows/exec-pipeline.yml
    strategy:
      matrix:
        include:
          - env: dv
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: pr
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: dv
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/services/

          - env: pr
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/services/
    with:
      env: ${{ matrix.env }}
      provider: ${{ matrix.provider }}
      tfvars_path: ${{ matrix.tfvars_path }}
      trigger_path: ${{ matrix.trigger_path }}