name: Terraform Filter

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Izaberi okruženje"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd
      provider:
        description: "Izaberi provider"
        required: true
        default: "common_infrastructure"
        type: choice
        options:
          - common_infrastructure
          - services

  push:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

jobs:
  terraform:
    name: Terraform Deploy - ${{ matrix.env }} - ${{ matrix.provider }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: dev
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: prd
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: dev
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/services/

          - env: prd
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/services/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get modified files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.before }}
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Modified files: $MODIFIED_FILES"
          echo "modified<<EOF" >> $GITHUB_OUTPUT
          echo "$MODIFIED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Decide if Terraform should run
        id: should_run
        run: |
          MODIFIED_FILES="${{ steps.changed_files.outputs.modified }}"
          echo "Modified files: $MODIFIED_FILES"

          if [[ "$MODIFIED_FILES" == *"infrastructure/modules/"* ]] || \
             [[ "$MODIFIED_FILES" == *"${{ matrix.tfvars_path }}"* ]] || \
             [[ "$MODIFIED_FILES" == *"${{ matrix.trigger_path }}"* ]]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Terraform
        if: steps.should_run.outputs.run == 'true' || github.event_name == 'workflow_dispatch'
        uses: ./.github/workflows/terraform-exec.yml
        with:
          env: ${{ github.event.inputs.env || matrix.env }}
          provider: ${{ github.event.inputs.provider || matrix.provider }}