name: Terraform Filter

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose env"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd
      provider:
        description: "Choose provider"
        required: true
        default: "common_infrastructure"
        type: choice
        options:
          - common_infrastructure
          - services

  push:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

  pull_request:
    branches: ["*"]
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/deployment/**'

jobs:
  terraform:
    name: Terraform Deploy - ${{ matrix.env }} - ${{ matrix.provider }}
    uses: ./.github/workflows/exec-pipeline.yml
    strategy:
      matrix:
        include:
          - env: dev
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: prd
            provider: common_infrastructure
            tfvars_path: infrastructure/deployment/common_infrastructure/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/common_infrastructure/

          - env: dev
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/dev.tfvars
            trigger_path: infrastructure/deployment/services/

          - env: prd
            provider: services
            tfvars_path: infrastructure/deployment/services/varvalues/prd.tfvars
            trigger_path: infrastructure/deployment/services/
    with:
      env: ${{ github.event.inputs.env || matrix.env }}
      provider: ${{ github.event.inputs.provider || matrix.provider }}
      tfvars_path: ${{ github.event.inputs.env && github.event.inputs.provider && format('infrastructure/deployment/{0}/varvalues/{1}.tfvars', github.event.inputs.provider, github.event.inputs.env) || matrix.tfvars_path }}
      trigger_path: ${{ github.event.inputs.env && github.event.inputs.provider && format('infrastructure/deployment/{0}/', github.event.inputs.provider) || matrix.trigger_path }}